### ISSUE TITLE
Port to python 3

### ISSUE THREAD

**Issue by rkern** [enthought/qt_binder#13]

**Comment by itziakos** [comment]
I think that this has been implemented

**Comment by rkern** [comment]
Well, the tests run, but I'm having trouble running any of the examples due to `traitsui` not working on Python 3.4. It uses `basestring` everywhere.

**Comment by rkern** [comment]
Never mind. I think I fixed that one. But I still want to actually personally run the examples under Python 3 before closing this. :-)

**Comment by rkern** [comment]
There's a bug in `examples/range_slider.py` that doesn't occur under Python 2:

```
$ python3 range_slider.py                                                                                                                                                                                      :master
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: RangeSlider(), trait: range, old value: (0, 99), new value: (-10.0, 10.0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/usr/local/lib/python3.4/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/usr/local/lib/python3.4/site-packages/qt_binder/widgets.py", line 485, in _update_widgets
    self.slider.range = range
  File "/usr/local/lib/python3.4/site-packages/traits/trait_handlers.py", line 173, in error
    value )
traits.trait_errors.TraitError: The 'range' trait of an IntSlider instance must be a tuple of the form: (an integer (int or long), an integer (int or long)), but a value of (-10.0, 10.0) <class 'tuple'> was specified.
Exception occurred in traits notification handler for object: RangeSlider(), trait: range, old value: (0, 99), new value: (0.5, 2.0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/usr/local/lib/python3.4/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/usr/local/lib/python3.4/site-packages/qt_binder/widgets.py", line 485, in _update_widgets
    self.slider.range = range
  File "/usr/local/lib/python3.4/site-packages/traits/trait_handlers.py", line 173, in error
    value )
traits.trait_errors.TraitError: The 'range' trait of an IntSlider instance must be a tuple of the form: (an integer (int or long), an integer (int or long)), but a value of (0.5, 2.0) <class 'tuple'> was specified.
```

**Comment by rkern** [comment]
`examples/convert_units.py` doesn't work either, but only because its `scimath` dependency hasn't been ported yet, so that's fine.

**Comment by rkern** [comment]
Ah, random hash seed changes the order in which the `range` and `slider` keywords got assigned. Looking into it.
