### ISSUE TITLE
Cannot set alignment in GroupBox

### ISSUE THREAD

**Issue by pberkes** [enthought/qt_binder#36]
Trying to set the `alignment` attribute of a `GroupBox` fails with this traceback:

```
Exception occurred in traits notification handler for object: GroupBox(), trait: qobj, old value: None, new value: <PySide.QtGui.QGroupBox object at 0x117474998>
Traceback (most recent call last):
  File "build/bdist.macosx-10.6-x86_64/egg/traits/trait_notifiers.py", line 340, in __call__
  File "/Users/pberkes/egit/qt_binder/qt_binder/binder.py", line 611, in _qobj_changed
    self.trait_set(**values)
  File "build/bdist.macosx-10.6-x86_64/egg/traits/has_traits.py", line 1545, in trait_set
  File "/Users/pberkes/egit/qt_binder/qt_binder/binder.py", line 162, in set
    old = self.get(object, name)
  File "/Users/pberkes/egit/qt_binder/qt_binder/binder.py", line 143, in get
    value = self.meta_prop.read(qobj)
RuntimeError: Can't find converter for 'Qt::Alignment'.
```

Example:

```
from traits.api import HasStrictTraits
from traitsui.api import View

from qt_binder.bound_editor import Bound
from qt_binder.qt import QtCore
from qt_binder.raw_widgets import GroupBox, Label, VBoxLayout


class Model(HasStrictTraits):

    def default_traits_view(self):
        traits_view = View(
            Bound(
                GroupBox(
                    VBoxLayout(
                        Label(text='Hi'),
                    ),
                    title=u'Time',
                    alignment=QtCore.Qt.AlignRight,
                ),
            ),
            resizable=True,
            width=300,
            height=200,
        )
        return traits_view


if __name__ == '__main__':
    m = Model()
    m.configure_traits()
```

**Comment by rkern** [comment]
`<grumbles>` PySide bug.
