### ISSUE TITLE
2 python 3.5 test errors

### ISSUE THREAD

**Issue by cournape** [enthought/qt_binder#50]
With python 3.5.2, traitsui/pyface/pyqt from edm, I see the following:

```
======================================================================
ERROR: test_object_traits (qt_binder.tests.test_binder.TestBinder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vagrant/.edm-build/envs/build-env/lib/python3.5/site-packages/qt_binder/tests/test_binder.py", line 62, in test_object_traits
    self.assertIsInstance(traits['destroyed_QObject'], QtSignal)
KeyError: 'destroyed_QObject'

======================================================================
FAIL: test_delayed_connection (qt_binder.tests.test_binder.TestBinder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vagrant/.edm-build/envs/build-env/lib/python3.5/site-packages/qt_binder/tests/test_binder.py", line 196, in test_delayed_connection
    six.assertCountEqual(self, received, [(), qobj])
  File "/Users/vagrant/.edm-build/envs/build-env/lib/python3.5/site-packages/six.py", line 667, in assertCountEqual
    return getattr(self, _assertCountEqual)(*args, **kwargs)
AssertionError: Element counts were not equal:
First has 0, Second has 1:  <PyQt4.QtCore.QObject object at 0x113557a68>

----------------------------------------------------------------------
```

Those are on OS X, but I also see them on linux

**Comment by jvkersch** [comment]
@rkern This is fixed by https://github.com/enthought/qt_binder/pull/48, OK to close this?
