### ISSUE TITLE
Failures with Qt 6 on Python 3.8

### ISSUE THREAD

**Issue by itziakos** [enthought/qt_binder#65]
Test failures when running tests on Python 3.8 using Qt6 (PySide6)
```
[2022-04-21T19:00:40.900Z] ======================================================================
[2022-04-21T19:00:40.900Z] ERROR: test_delayed_connection (qt_binder.tests.test_binder.TestBinder)
[2022-04-21T19:00:40.900Z] ----------------------------------------------------------------------
[2022-04-21T19:00:40.900Z] Traceback (most recent call last):
[2022-04-21T19:00:40.900Z]   File "/home/vagrant/.edm/envs/build-env/lib/python3.8/site-packages/qt_binder/tests/test_binder.py", line 200, in test_delayed_connection
[2022-04-21T19:00:40.900Z]     obj.on_trait_change(handler, 'destroyed', remove=True)
[2022-04-21T19:00:40.900Z]   File "/home/vagrant/.edm/envs/build-env/lib/python3.8/site-packages/traits/has_traits.py", line 2646, in on_trait_change
[2022-04-21T19:00:40.900Z]     self._on_trait_change(
[2022-04-21T19:00:40.900Z]   File "/home/vagrant/.edm/envs/build-env/lib/python3.8/site-packages/qt_binder/binder.py", line 565, in _on_trait_change
[2022-04-21T19:00:40.900Z]     func(self, name)
[2022-04-21T19:00:40.900Z]   File "/home/vagrant/.edm/envs/build-env/lib/python3.8/site-packages/qt_binder/binder.py", line 153, in disconnect_signal
[2022-04-21T19:00:40.900Z]     signal.disconnect(slot)
[2022-04-21T19:00:40.900Z] RuntimeError: Failed to disconnect signal destroyed().
[2022-04-21T19:00:40.900Z] 
[2022-04-21T19:00:40.900Z] ======================================================================
[2022-04-21T19:00:40.900Z] ERROR: Failure: AttributeError (module 'qt_binder.qt.QtGui' has no attribute 'QDesktopWidget')
[2022-04-21T19:00:40.900Z] ----------------------------------------------------------------------
[2022-04-21T19:00:40.900Z] Traceback (most recent call last):
[2022-04-21T19:00:40.900Z]   File "/home/vagrant/.edm/envs/build-env/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
[2022-04-21T19:00:40.901Z]     raise self.exc_val.with_traceback(self.tb)
[2022-04-21T19:00:40.901Z]   File "/home/vagrant/.edm/envs/build-env/lib/python3.8/site-packages/nose/loader.py", line 418, in loadTestsFromName
[2022-04-21T19:00:40.901Z]     module = self.importer.importFromPath(
[2022-04-21T19:00:40.901Z]   File "/home/vagrant/.edm/envs/build-env/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
[2022-04-21T19:00:40.901Z]     return self.importFromDir(dir_path, fqname)
[2022-04-21T19:00:40.901Z]   File "/home/vagrant/.edm/envs/build-env/lib/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
[2022-04-21T19:00:40.901Z]     mod = load_module(part_fqname, fh, filename, desc)
[2022-04-21T19:00:40.901Z]   File "/home/vagrant/.edm/envs/build-env/lib/python3.8/imp.py", line 234, in load_module
[2022-04-21T19:00:40.901Z]     return load_source(name, filename, file)
[2022-04-21T19:00:40.901Z]   File "/home/vagrant/.edm/envs/build-env/lib/python3.8/imp.py", line 171, in load_source
[2022-04-21T19:00:40.901Z]     module = _load(spec)
[2022-04-21T19:00:40.901Z]   File "<frozen importlib._bootstrap>", line 702, in _load
[2022-04-21T19:00:40.901Z]   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[2022-04-21T19:00:40.901Z]   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
[2022-04-21T19:00:40.901Z]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[2022-04-21T19:00:40.901Z]   File "/home/vagrant/.edm/envs/build-env/lib/python3.8/site-packages/qt_binder/tests/test_raw_widgets.py", line 19, in <module>
[2022-04-21T19:00:40.901Z]     from ..raw_widgets import BasicGridLayout, GroupBox, HBoxLayout, Label, \
[2022-04-21T19:00:40.901Z]   File "/home/vagrant/.edm/envs/build-env/lib/python3.8/site-packages/qt_binder/raw_widgets.py", line 42, in <module>
[2022-04-21T19:00:40.901Z]     class DesktopWidget(Binder):
[2022-04-21T19:00:40.901Z]   File "/home/vagrant/.edm/envs/build-env/lib/python3.8/site-packages/qt_binder/raw_widgets.py", line 43, in DesktopWidget
[2022-04-21T19:00:40.901Z]     qclass = QtGui.QDesktopWidget
[2022-04-21T19:00:40.901Z] AttributeError: module 'qt_binder.qt.QtGui' has no attribute 'QDesktopWidget'
```

**Comment by rkern** [comment]
Fixed by #66
